backend:
  name: git-gateway
  branch: main
media_folder: "raw_img/uploads"
collections:
  - name: "works"
    label: "Portfolio"
    folder: "works"
    create: true
    slug: ""
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "work"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "text"}