backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio-item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured image", name: "image", widget: "image"}
