backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/imgs"
public_folder: "/imgs"
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "portfolio" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          time_format: false,
          date_format: "YYYY-MM-DD",
          format: "YYYY-MM-DD",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured image", name: "image", widget: "image" }
      - { label: "ImgAlt", name: "imgAlt", widget: "text" }
      - { label: "Url", name: "url", widget: "text" }
